apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-apps-of-apps
  namespace: argocd
spec:
  syncPolicy:
    automated:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/vaisanenj/K3s-cluster-setup.git
        revision: main
        directories:
          - path: kubernetes/apps/gitea
          - path: kubernetes/apps/openldap
          - path: kubernetes/apps/gameserver-enshrouded/overlay/*
          - path: kubernetes/apps/gameserver-palworld/overlay/*
          - path: kubernetes/apps/gameserver-valheim/overlay/*
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'
      source:
        repoURL: https://github.com/vaisanenj/K3s-cluster-setup.git
        path: '{{.path.path}}'
        targetRevision: main
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false