apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-myapps
  namespace: argocd
spec:
  syncPolicy:
    automated:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: http://svc-gitea.gitea:3000/vaisajon/Kube-apps
        revision: HEAD
        directories:
          - path: kubernetes/apps/*
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'
      source:
        repoURL: http://svc-gitea.gitea:3000/vaisajon/Kube-apps
        path: '{{.path.path}}'
        targetRevision: HEAD
        directory:
          recurse: false
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false