apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-system-setup
  namespace: argocd
spec:
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
          - key: application
            operator: In
            values:
              - external-secrets
              - intel-device-manager
              - metallb-system
        - matchExpressions:
          - key: application
            operator: In
            values:
              - cert-manager
              - traefik
          maxUpdate: 0
        - matchExpressions:
          - key: application
            operator: In
            values:
              - longhorn-system
        - matchExpressions:
          - key: application
            operator: In
            values:
              - kube-prometheus-stack
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/vaisanenj/K3s-cluster-setup.git
        revision: dev
        directories:
          - path: kubernetes/system/*/*
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
      labels:
        sync-wave: '{{index .path.segments 2}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'
      source:
        repoURL: https://github.com/vaisanenj/K3s-cluster-setup.git
        path: '{{.path.path}}'
        targetRevision: dev
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - Validate=false