apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: palworld
spec:
  replicas: 1
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn-rc-2
      resources:
        requests:
          storage: 20Gi
  template:
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-palworld
      containers:
      - name: palworld
        image: thijsvanloef/palworld-server-docker:v1.4.3
        ports:
        - containerPort: 15637
          name: queryport
        resources:
          requests:
            cpu: "2500m"
            memory: "4Gi"
          limits:
            cpu: "4000m"
            memory: "8Gi"
        envFrom:
          - configMapRef:
              name: configmap-env
        env:
        - name: SERVER_NAME
          valueFrom:
            secretKeyRef:
              name: palworld-secrets
              key: name
        - name: SERVER_DESCRIPTION
          valueFrom:
            secretKeyRef:
              name: palworld-secrets
              key: desc
        - name: SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: palworld-secrets
              key: password
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: palworld-secrets
              key: admin-password
        volumeMounts:
          - name: data
            mountPath: /palworld