longhorn:
  preUpgradeChecker:
    jobEnabled: false
  
  defaultSettings:
    defaultDataPath: /mnt/longhorn
  persistence:
    defaultClass: true
    defaultClassName: "longhorn-strict-local-1-replica" 
  defaultBackupStore:
    backupTarget: "s3://longhorn.garage.truenas@garage/longhorn"
    backupTargetCredentialSecret: "s3-garage-credentials"