longhorn:
  preUpgradeChecker:
    jobEnabled: false
  
  defaultSettings:
    defaultDataPath: /mnt/longhorn

  defaultBackupStore:
    backupTarget: "s3://longhorn.garage.truenas@garage/longhorn"
    backupTargetCredentialSecret: "s3-garage-credentials"
    pollInterval: 5m0s