kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-strict-local-1-replica
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "strict-local"