apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://192.168.20.230:8200"
      path: "K3s-secrets"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "default"
          key: "token"