apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - externalsecret.yaml

configMapGenerator:
  - name: configmap
    env: config.properties

patches:
  - target:
      kind: Service
      name: svc-enshrouded
    patch: |
      - op: replace
        path: /spec/ports/0/port
        value: 15638