apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-externalsecret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target: 
    name: crowdsec-secrets
  data:
  - secretKey: enroll-key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: ENROLL_KEY
      key: crowdsec
      metadataPolicy: None