apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-externalsecret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: s3-garage-credentials
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: AWS_ACCESS_KEY_ID
      key: lognhorn-system
      metadataPolicy: None
  - secretKey: AWS_ENDPOINTS
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: AWS_ENDPOINTS
      key: longhorn-system
      metadataPolicy: None
  - secretKey: AWS_REGION
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: AWS_REGION
      key: longhorn-system
      metadataPolicy: None
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: AWS_SECRET_ACCESS_KEY
      key: longhorn-system
      metadataPolicy: None
