kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-2rep-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "1440" # 1 day
  dataLocality: "best-effort"