apiVersion: v1
kind: Service
metadata:
  name: svc-lyrion-media-server
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.20.210
  externalTrafficPolicy: Local
  ports:
    - name: port
      port: 9000
      protocol: TCP
    - name: port9090
      port: 9090
      protocol: TCP
    - name: port3483tcp
      port: 3483
      protocol: TCP
    - name: port3483udp
      port: 3483
      protocol: UDP