immich:
  controllers:
    main:
      replicas: 0
      containers:
        main:
          image:
            tag: v2.0.0
          env:
            DB_HOSTNAME: immich-database-rw
            DB_USERNAME:
              valueFrom:
                secretKeyRef:
                  name: db-app-user
                  key: username
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: db-app-user
                  key: password
            DB_DATABASE_NAME: immich
  immich:
    persistence:
      library:
        existingClaim: immich-library-pvc

  valkey:
    enabled: true