apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valheim
spec:
  replicas: 0
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn-rc-2
      resources:
        requests:
          storage: 20Gi
  template:
    spec:
      containers:
        - name: valheim
          image: lloesche/valheim-server
          resources:
              requests:
                cpu: "500m"
                memory: "2Gi"
              limits:
                cpu: "4000m"
                memory: "6Gi"
          envFrom:
            - configMapRef:
                name: configmap-env
          env:
          - name: PRE_UPDATE_CHECK_HOOK #Temp fix 
            value: "sed -i -e s,Valheim/\",Valheim/5.4.2202/\", -e s,\\.latest\\.download_url,\\.download_url, /usr/local/bin/bepinex-updater"
          - name: SERVER_NAME
            valueFrom:
              secretKeyRef:
                name: valheim-secrets
                key: SERVER_NAME
          - name: SERVER_PASS
            valueFrom:
              secretKeyRef:
                name: valheim-secrets
                key: SERVER_PASS
          volumeMounts:
            - name: data
              subPath: config
              mountPath: /config
            - name: data
              subPath: data
              mountPath: /opt/valheim