apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enshrouded
spec:
  replicas: 0
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn-rc-2
      resources:
        requests:
          storage: 15Gi
  template:
    spec:
      containers:
      - name: enshourded
        image: mornedhels/enshrouded-server:stable-proton
        ports:
        - containerPort: 15637
          name: queryport
        resources:
          requests:
            cpu: "1500m"
            memory: "2Gi"
          limits:
            cpu: "4000m"
            memory: "6Gi"
        envFrom:
          - configMapRef:
              name: configmap
        env:
        - name: SERVER_NAME
          valueFrom:
            secretKeyRef:
              name: enshrouded-secrets
              key: SERVER_NAME
        - name: SERVER_ROLE_0_NAME
          valueFrom:
            secretKeyRef:
              name: enshrouded-secrets
              key: SERVER_ROLE_0_NAME
        - name: SERVER_ROLE_0_PASSWORD
          valueFrom:
            secretKeyRef:
              name: enshrouded-secrets
              key: SERVER_ROLE_0_PASSWORD
        - name: SERVER_ROLE_1_NAME
          valueFrom:
            secretKeyRef:
              name: enshrouded-secrets
              key: SERVER_ROLE_1_NAME
        - name: SERVER_ROLE_1_PASSWORD
          valueFrom:
            secretKeyRef:
              name: enshrouded-secrets
              key: SERVER_ROLE_1_PASSWORD
        volumeMounts:
          - name: data
            mountPath: /opt/enshrouded