apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-app-user
spec:
  refreshInterval: "30m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: db-app-user
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
  - secretKey: username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: DB_APP_USER
      key: immich
      metadataPolicy: None
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: DB_APP_PASS
      key: immich
      metadataPolicy: None