apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-ingressroute
spec:
  entryPoints:
    - local-https
    - local-http
  routes:
  - kind: Rule
    match: Host(`immich.local`)
    services:
    - kind: Service
      name: immich-server
      port: 2283
