crowdsec:
  container_runtime: containerd   # for raw logs format: json or cri (docker|containerd)
  agent:
    acquisition:                  # Specify each pod whose logs you want to process
      - namespace: traefik        # The namespace where the pod is located
        podName: traefik-*        # The pod name
        program: traefik          # as in crowdsec configuration, we need to specify the program name to find a matching parser
    env:
      - name: COLLECTIONS
        value: "crowdsecurity/traefik"
  lapi:
    env:
      # To enroll the Security Engine to the console
      - name: ENROLL_KEY
        valueFrom:
          secretKeyRef:
            name: crowdsec-secrets
            key: enroll-key
      - name: ENROLL_INSTANCE_NAME
        value: "my-k8s-cluster"
      - name: ENROLL_TAGS
        value: "k8s linux test"