apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-externalsecret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target: 
    name: cloudflare-api-token-secret
  data:
  - secretKey: api-token
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: api-token
      key: cert-manager
      metadataPolicy: None